### PR TITLE
modify Vagrantfile to make it more flexible, scalable and easy extend…

### PR DESCRIPTION
**Pull request by ghost**
…ible

fix centos issues for virtualbox 5.1.21
update used ubuntu box version from 14.04 to 16.04
add bridged networking option

### CODE REVIEW

**Comment by marco-m** [comment]
Hello @UtahDave, would you consider this PR? I like how it makes the Vagrantfile more parametric. On the other hand it contains multiple independent changes, maybe you could ask @readonlysc to split in separate PRs ?

**Comment by ghost** [comment]
@marco-m how should I split my pull request? I mean in which two parts? thank you for your comment.

**Comment by marco-m** [comment]
@readonlysc To me, the most important change is the parametric approach. So first PR could be only that, without the bridge and keeping the Ubuntu VM. Second PR could be the bridge, 3rd PR the addition of Centos.

**Comment by ghost** [comment]
@marco-m I did the changes, i think know it should be ready for the merge
thank you for your tipps

**Comment by marco-m** [comment]
@readonlysc You are welcome! Let's see if @UtahDave is still interested in this repo...

**Comment by UtahDave** [comment]
Thanks for this update!  Sorry it took me a while to get to test it.

**Comment by marco-m** [comment]
Thanks!

**Pull request merged**
